# Generated by Django 2.0.6 on 2018-08-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=100)),
                ('mac_address', models.CharField(default='Unknown', max_length=17)),
                ('ip_address', models.CharField(default='127.0.0.1', max_length=45)),
                ('vendor', models.CharField(default='Unknown', max_length=100)),
                ('serial_number', models.CharField(default='Unknown', max_length=100)),
                ('is_wireless', models.BooleanField(default=True)),
                ('building_address', models.CharField(default='None', max_length=100)),
                ('building_name', models.CharField(default='None', max_length=100)),
                ('building_floor', models.CharField(default='None', max_length=100)),
                ('access_point', models.CharField(default='None', max_length=100)),
                ('connection_time', models.CharField(default='Unknown', max_length=100)),
                ('signal_strength', models.CharField(default='Unknown', max_length=100)),
                ('second_ap', models.CharField(default='Unknown', max_length=100)),
                ('third_ap', models.CharField(default='Unknown', max_length=100)),
                ('fourth_ap', models.CharField(default='Unknown', max_length=100)),
                ('fifth_ap', models.CharField(default='Unknown', max_length=100)),
                ('sixth_ap', models.CharField(default='Unknown', max_length=100)),
                ('switch', models.CharField(default='Unknown', max_length=100)),
                ('switch_location', models.CharField(default='Unknown', max_length=100)),
                ('switch_port', models.IntegerField(default=0)),
                ('last_seen', models.CharField(default='Unknown', max_length=100)),
                ('first_discovered', models.CharField(default='Unknown', max_length=100)),
                ('assigned_user', models.CharField(default='None', max_length=100)),
                ('last_login_user', models.CharField(default='None', max_length=100)),
                ('last_login_date', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
    ]
