# Generated by Django 2.0.6 on 2018-06-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='access_point',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='assigned_user',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='building_address',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='building_floor',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='building_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='last_login_user',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='signal_strength',
            field=models.IntegerField(default=0),
        ),
    ]
