# Generated by Django 2.0.6 on 2018-06-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20180615_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ip_address',
            field=models.CharField(default='127.0.0.1', max_length=45),
        ),
        migrations.AddField(
            model_name='device',
            name='mac_address',
            field=models.CharField(default='Unknown', max_length=17),
        ),
    ]
