# Generated by Django 2.0.6 on 2018-06-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20180618_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_login_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
