# Generated by Django 2.0.6 on 2018-06-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_device_last_login_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='connection_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='last_five_access_points',
            field=models.CharField(default='None, None, None, None, None', max_length=200),
        ),
        migrations.AddField(
            model_name='device',
            name='vendor',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
