# Generated by Django 2.0.6 on 2018-06-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20180622_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_wireless',
            field=models.BooleanField(default=True),
        ),
    ]
