# Generated by Django 2.0.6 on 2018-06-27 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_device_is_wireless'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_address', models.CharField(default='Unknown', max_length=100)),
                ('ap_id', models.CharField(default='Unknown', max_length=100)),
                ('connection_time', models.DurationField()),
                ('disconnection_time', models.DateTimeField()),
                ('rssi', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_address', models.CharField(default='Unknown', max_length=100)),
                ('switch_id', models.CharField(default='Unknown', max_length=100)),
                ('connection_time', models.DurationField()),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='access_point',
        ),
        migrations.RemoveField(
            model_name='device',
            name='connection_time',
        ),
        migrations.RemoveField(
            model_name='device',
            name='last_five_access_points',
        ),
        migrations.RemoveField(
            model_name='device',
            name='signal_strength',
        ),
        migrations.AddField(
            model_name='switch',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Device'),
        ),
        migrations.AddField(
            model_name='device',
            name='current_ap',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='current access point +', to='report.AccessPoint'),
        ),
        migrations.AddField(
            model_name='device',
            name='fifth_node',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='fifth access point +', to='report.AccessPoint'),
        ),
        migrations.AddField(
            model_name='device',
            name='first_node',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='first access point +', to='report.AccessPoint'),
        ),
        migrations.AddField(
            model_name='device',
            name='fourth_node',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='fourth access point +', to='report.AccessPoint'),
        ),
        migrations.AddField(
            model_name='device',
            name='second_node',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='second access point +', to='report.AccessPoint'),
        ),
        migrations.AddField(
            model_name='device',
            name='third_node',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='third access point +', to='report.AccessPoint'),
        ),
    ]
