# Generated by Django 2.0.6 on 2018-07-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_device_is_wireless'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='last_five_access_points',
        ),
        migrations.AddField(
            model_name='device',
            name='fifth_ap',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='first_discovered',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='fourth_ap',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='last_seen',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='second_ap',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='sixth_ap',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='switch',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='switch_location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='switch_port',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='third_ap',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='connection_time',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_login_date',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='signal_strength',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
