# Generated by Django 2.0.6 on 2018-07-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20180627_1532'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessPoint',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='device',
        ),
        migrations.RemoveField(
            model_name='device',
            name='current_ap',
        ),
        migrations.RemoveField(
            model_name='device',
            name='fifth_node',
        ),
        migrations.RemoveField(
            model_name='device',
            name='first_node',
        ),
        migrations.RemoveField(
            model_name='device',
            name='fourth_node',
        ),
        migrations.RemoveField(
            model_name='device',
            name='second_node',
        ),
        migrations.RemoveField(
            model_name='device',
            name='third_node',
        ),
        migrations.AddField(
            model_name='device',
            name='access_point',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='connection_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='last_five_access_points',
            field=models.CharField(default='None, None, None, None, None', max_length=200),
        ),
        migrations.AddField(
            model_name='device',
            name='signal_strength',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Switch',
        ),
    ]
