# Generated by Django 2.0.6 on 2018-07-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20180716_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
